// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.0.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Euro.PatientPortal.PatientPortalAPI.Test.APITest.Features.Usercreation
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("UserCreationNTDBU")]
    public partial class UserCreationNTDBUFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "UserCreationNTDBU.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "UserCreationNTDBU", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
                    "f two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("1 Create Users and set Password Report first")]
        [NUnit.Framework.CategoryAttribute("api")]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "1", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "2", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "3", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "4", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "5", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "6", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "7", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "8", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "9", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "10", null)]
        public virtual void _1CreateUsersAndSetPasswordReportFirst(string bu, string email, string reportname, string numOfReports, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "api"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("1 Create Users and set Password Report first", @__tags);
#line 7
  this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given(string.Format("I send report \"{0}\" for the user \"User\" with email \"{1}\" for Bu \"{2}\"", reportname, email, bu), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.When("I Create User \"User\" and note referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.And("I set password \"Eurofins@2020\" for created User \"User\" with referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And(string.Format("I add \"{0}\" reports for user \"User\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And(string.Format("I added User creds username \"User\" password \"Eurofins@2020\" and number of reports" +
                        " added \"{0}\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("2 Create Users and set Password Report first")]
        [NUnit.Framework.CategoryAttribute("api")]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "1", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "2", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "3", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "4", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "5", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "6", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "7", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "8", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "9", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "10", null)]
        public virtual void _2CreateUsersAndSetPasswordReportFirst(string bu, string email, string reportname, string numOfReports, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "api"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2 Create Users and set Password Report first", @__tags);
#line 29
 this.ScenarioSetup(scenarioInfo);
#line 31
 testRunner.Given(string.Format("I send report \"{0}\" for the user \"User\" with email \"{1}\" for Bu \"{2}\"", reportname, email, bu), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 32
 testRunner.When("I Create User \"User\" and note referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 33
 testRunner.And("I set password \"Eurofins@2020\" for created User \"User\" with referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.And(string.Format("I add \"{0}\" reports for user \"User\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
 testRunner.And(string.Format("I added User creds username \"User\" password \"Eurofins@2020\" and number of reports" +
                        " added \"{0}\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("3 Create Users and set Password Report first")]
        [NUnit.Framework.CategoryAttribute("api")]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "1", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "2", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "3", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "4", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "5", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "6", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "7", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "8", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "9", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "10", null)]
        public virtual void _3CreateUsersAndSetPasswordReportFirst(string bu, string email, string reportname, string numOfReports, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "api"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("3 Create Users and set Password Report first", @__tags);
#line 51
 this.ScenarioSetup(scenarioInfo);
#line 53
 testRunner.Given(string.Format("I send report \"{0}\" for the user \"User\" with email \"{1}\" for Bu \"{2}\"", reportname, email, bu), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 54
 testRunner.When("I Create User \"User\" and note referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 55
 testRunner.And("I set password \"Eurofins@2020\" for created User \"User\" with referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 56
 testRunner.And(string.Format("I add \"{0}\" reports for user \"User\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.And(string.Format("I added User creds username \"User\" password \"Eurofins@2020\" and number of reports" +
                        " added \"{0}\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("4 Create Users and set Password Report first")]
        [NUnit.Framework.CategoryAttribute("api")]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "1", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "2", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "3", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "4", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "5", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "6", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "7", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "8", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "9", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "10", null)]
        public virtual void _4CreateUsersAndSetPasswordReportFirst(string bu, string email, string reportname, string numOfReports, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "api"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("4 Create Users and set Password Report first", @__tags);
#line 73
 this.ScenarioSetup(scenarioInfo);
#line 75
 testRunner.Given(string.Format("I send report \"{0}\" for the user \"User\" with email \"{1}\" for Bu \"{2}\"", reportname, email, bu), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 76
 testRunner.When("I Create User \"User\" and note referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 77
 testRunner.And("I set password \"Eurofins@2020\" for created User \"User\" with referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
 testRunner.And(string.Format("I add \"{0}\" reports for user \"User\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
 testRunner.And(string.Format("I added User creds username \"User\" password \"Eurofins@2020\" and number of reports" +
                        " added \"{0}\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("5 Create Users and set Password Report first")]
        [NUnit.Framework.CategoryAttribute("api")]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "1", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "2", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "3", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "4", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "5", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "6", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "7", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "8", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "9", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "10", null)]
        public virtual void _5CreateUsersAndSetPasswordReportFirst(string bu, string email, string reportname, string numOfReports, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "api"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5 Create Users and set Password Report first", @__tags);
#line 95
 this.ScenarioSetup(scenarioInfo);
#line 97
 testRunner.Given(string.Format("I send report \"{0}\" for the user \"User\" with email \"{1}\" for Bu \"{2}\"", reportname, email, bu), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 98
 testRunner.When("I Create User \"User\" and note referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 99
 testRunner.And("I set password \"Eurofins@2020\" for created User \"User\" with referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 100
 testRunner.And(string.Format("I add \"{0}\" reports for user \"User\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 101
 testRunner.And(string.Format("I added User creds username \"User\" password \"Eurofins@2020\" and number of reports" +
                        " added \"{0}\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("6 Create Users and set Password Report first")]
        [NUnit.Framework.CategoryAttribute("api")]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "1", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "2", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "3", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "4", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "5", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "6", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "7", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "8", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "9", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "10", null)]
        public virtual void _6CreateUsersAndSetPasswordReportFirst(string bu, string email, string reportname, string numOfReports, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "api"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("6 Create Users and set Password Report first", @__tags);
#line 117
 this.ScenarioSetup(scenarioInfo);
#line 119
 testRunner.Given(string.Format("I send report \"{0}\" for the user \"User\" with email \"{1}\" for Bu \"{2}\"", reportname, email, bu), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 120
 testRunner.When("I Create User \"User\" and note referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 121
 testRunner.And("I set password \"Eurofins@2020\" for created User \"User\" with referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 122
 testRunner.And(string.Format("I add \"{0}\" reports for user \"User\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 123
 testRunner.And(string.Format("I added User creds username \"User\" password \"Eurofins@2020\" and number of reports" +
                        " added \"{0}\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("7 Create Users and set Password Report first")]
        [NUnit.Framework.CategoryAttribute("api")]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "1", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "2", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "3", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "4", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "5", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "6", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "7", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "8", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "9", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "10", null)]
        public virtual void _7CreateUsersAndSetPasswordReportFirst(string bu, string email, string reportname, string numOfReports, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "api"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("7 Create Users and set Password Report first", @__tags);
#line 139
 this.ScenarioSetup(scenarioInfo);
#line 141
 testRunner.Given(string.Format("I send report \"{0}\" for the user \"User\" with email \"{1}\" for Bu \"{2}\"", reportname, email, bu), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 142
 testRunner.When("I Create User \"User\" and note referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 143
 testRunner.And("I set password \"Eurofins@2020\" for created User \"User\" with referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 144
 testRunner.And(string.Format("I add \"{0}\" reports for user \"User\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 145
 testRunner.And(string.Format("I added User creds username \"User\" password \"Eurofins@2020\" and number of reports" +
                        " added \"{0}\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("8 Create Users and set Password Report first")]
        [NUnit.Framework.CategoryAttribute("api")]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "1", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "2", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "3", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "4", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "5", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "6", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "7", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "8", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "9", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "10", null)]
        public virtual void _8CreateUsersAndSetPasswordReportFirst(string bu, string email, string reportname, string numOfReports, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "api"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("8 Create Users and set Password Report first", @__tags);
#line 161
 this.ScenarioSetup(scenarioInfo);
#line 163
 testRunner.Given(string.Format("I send report \"{0}\" for the user \"User\" with email \"{1}\" for Bu \"{2}\"", reportname, email, bu), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 164
 testRunner.When("I Create User \"User\" and note referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 165
 testRunner.And("I set password \"Eurofins@2020\" for created User \"User\" with referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 166
 testRunner.And(string.Format("I add \"{0}\" reports for user \"User\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 167
 testRunner.And(string.Format("I added User creds username \"User\" password \"Eurofins@2020\" and number of reports" +
                        " added \"{0}\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("9 Create Users and set Password Report first")]
        [NUnit.Framework.CategoryAttribute("api")]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "1", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "2", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "3", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "4", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "5", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "6", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "7", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "8", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "9", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "10", null)]
        public virtual void _9CreateUsersAndSetPasswordReportFirst(string bu, string email, string reportname, string numOfReports, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "api"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("9 Create Users and set Password Report first", @__tags);
#line 183
 this.ScenarioSetup(scenarioInfo);
#line 185
 testRunner.Given(string.Format("I send report \"{0}\" for the user \"User\" with email \"{1}\" for Bu \"{2}\"", reportname, email, bu), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 186
 testRunner.When("I Create User \"User\" and note referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 187
 testRunner.And("I set password \"Eurofins@2020\" for created User \"User\" with referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 188
 testRunner.And(string.Format("I add \"{0}\" reports for user \"User\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 189
 testRunner.And(string.Format("I added User creds username \"User\" password \"Eurofins@2020\" and number of reports" +
                        " added \"{0}\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("10 Create Users and set Password Report first")]
        [NUnit.Framework.CategoryAttribute("api")]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "1", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "2", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "3", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "4", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "5", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "6", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "7", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "8", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "9", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "10", null)]
        public virtual void _10CreateUsersAndSetPasswordReportFirst(string bu, string email, string reportname, string numOfReports, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "api"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10 Create Users and set Password Report first", @__tags);
#line 205
 this.ScenarioSetup(scenarioInfo);
#line 207
 testRunner.Given(string.Format("I send report \"{0}\" for the user \"User\" with email \"{1}\" for Bu \"{2}\"", reportname, email, bu), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 208
 testRunner.When("I Create User \"User\" and note referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 209
 testRunner.And("I set password \"Eurofins@2020\" for created User \"User\" with referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 210
 testRunner.And(string.Format("I add \"{0}\" reports for user \"User\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 211
 testRunner.And(string.Format("I added User creds username \"User\" password \"Eurofins@2020\" and number of reports" +
                        " added \"{0}\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("11 Create Users and set Password Report first")]
        [NUnit.Framework.CategoryAttribute("api")]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "1", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "2", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "3", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "4", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "5", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "6", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "7", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "8", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "9", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "10", null)]
        public virtual void _11CreateUsersAndSetPasswordReportFirst(string bu, string email, string reportname, string numOfReports, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "api"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("11 Create Users and set Password Report first", @__tags);
#line 227
 this.ScenarioSetup(scenarioInfo);
#line 229
 testRunner.Given(string.Format("I send report \"{0}\" for the user \"User\" with email \"{1}\" for Bu \"{2}\"", reportname, email, bu), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 230
 testRunner.When("I Create User \"User\" and note referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 231
 testRunner.And("I set password \"Eurofins@2020\" for created User \"User\" with referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 232
 testRunner.And(string.Format("I add \"{0}\" reports for user \"User\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 233
 testRunner.And(string.Format("I added User creds username \"User\" password \"Eurofins@2020\" and number of reports" +
                        " added \"{0}\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("12 Create Users and set Password Report first")]
        [NUnit.Framework.CategoryAttribute("api")]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "1", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "2", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "3", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "4", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "5", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "6", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "7", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "8", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "9", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "10", null)]
        public virtual void _12CreateUsersAndSetPasswordReportFirst(string bu, string email, string reportname, string numOfReports, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "api"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("12 Create Users and set Password Report first", @__tags);
#line 249
 this.ScenarioSetup(scenarioInfo);
#line 251
 testRunner.Given(string.Format("I send report \"{0}\" for the user \"User\" with email \"{1}\" for Bu \"{2}\"", reportname, email, bu), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 252
 testRunner.When("I Create User \"User\" and note referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 253
 testRunner.And("I set password \"Eurofins@2020\" for created User \"User\" with referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 254
 testRunner.And(string.Format("I add \"{0}\" reports for user \"User\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 255
 testRunner.And(string.Format("I added User creds username \"User\" password \"Eurofins@2020\" and number of reports" +
                        " added \"{0}\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("13 Create Users and set Password Report first")]
        [NUnit.Framework.CategoryAttribute("api")]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "1", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "2", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "3", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "4", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "5", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "6", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "7", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "8", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "9", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "10", null)]
        public virtual void _13CreateUsersAndSetPasswordReportFirst(string bu, string email, string reportname, string numOfReports, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "api"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("13 Create Users and set Password Report first", @__tags);
#line 271
 this.ScenarioSetup(scenarioInfo);
#line 273
 testRunner.Given(string.Format("I send report \"{0}\" for the user \"User\" with email \"{1}\" for Bu \"{2}\"", reportname, email, bu), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 274
 testRunner.When("I Create User \"User\" and note referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 275
 testRunner.And("I set password \"Eurofins@2020\" for created User \"User\" with referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 276
 testRunner.And(string.Format("I add \"{0}\" reports for user \"User\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 277
 testRunner.And(string.Format("I added User creds username \"User\" password \"Eurofins@2020\" and number of reports" +
                        " added \"{0}\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("14 Create Users and set Password Report first")]
        [NUnit.Framework.CategoryAttribute("api")]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "1", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "2", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "3", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "4", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "5", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "6", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "7", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "8", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "9", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "10", null)]
        public virtual void _14CreateUsersAndSetPasswordReportFirst(string bu, string email, string reportname, string numOfReports, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "api"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("14 Create Users and set Password Report first", @__tags);
#line 293
 this.ScenarioSetup(scenarioInfo);
#line 295
 testRunner.Given(string.Format("I send report \"{0}\" for the user \"User\" with email \"{1}\" for Bu \"{2}\"", reportname, email, bu), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 296
 testRunner.When("I Create User \"User\" and note referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 297
 testRunner.And("I set password \"Eurofins@2020\" for created User \"User\" with referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 298
 testRunner.And(string.Format("I add \"{0}\" reports for user \"User\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 299
 testRunner.And(string.Format("I added User creds username \"User\" password \"Eurofins@2020\" and number of reports" +
                        " added \"{0}\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("15 Create Users and set Password Report first")]
        [NUnit.Framework.CategoryAttribute("api")]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "1", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "2", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "3", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "4", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "5", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "6", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "7", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report -286.pdf", "8", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "9", null)]
        [NUnit.Framework.TestCaseAttribute("NTD", "@GenerateRandomEmailWithDomain(dispostable.com)", "Ajeesh kv COVID-19 IgG Test Report - 285.pdf", "10", null)]
        public virtual void _15CreateUsersAndSetPasswordReportFirst(string bu, string email, string reportname, string numOfReports, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "api"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("15 Create Users and set Password Report first", @__tags);
#line 315
 this.ScenarioSetup(scenarioInfo);
#line 317
 testRunner.Given(string.Format("I send report \"{0}\" for the user \"User\" with email \"{1}\" for Bu \"{2}\"", reportname, email, bu), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 318
 testRunner.When("I Create User \"User\" and note referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 319
 testRunner.And("I set password \"Eurofins@2020\" for created User \"User\" with referenceId \"refId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 320
 testRunner.And(string.Format("I add \"{0}\" reports for user \"User\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 321
 testRunner.And(string.Format("I added User creds username \"User\" password \"Eurofins@2020\" and number of reports" +
                        " added \"{0}\"", numOfReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

